build:
  image: golang:latest
  script:
    - cd src
    - GOPATH=$CI_PROJECT_DIR/src:$GOPATH
    - go build -o ../bin/smitegods smitegods.go
  artifacts:
    paths:
      - bin/smitegods

pages:
  script:
  - mkdir public
  - cp roles-pantheons-spritesheet.png smitegods.css smitegods.html smitegods.js public
  - mv public/smitegods.html public/index.html
  artifacts:
    paths:
    - public
  only:
    - master
