
stages:
  - build_go
  - build_web
  - deploy

build_go:
  stage: build_go
  image: golang:latest
  script:
    - go build -o bin/smitegods src/cli/smitegods/smitegods.go
  artifacts:
    paths:
      - bin

build_web:
  stage: build_web
  script:
    - bin/smitegods -updategoddata -devid $SMITE_API_DEVID -authkey $SMITE_API_AUTHKEY
    - mkdir public
    - mkdir public/img
    - cp roles-pantheons-spritesheet.png 4bfba3d77789a9ec16129032096c7f12.woff smitegods.css smitegods.html smitegods.js public
    - cp godstats.css godstats.html godstats.js public
    - cp smiteitems.css smiteitems.html smiteitems.js public
    - cp god-skins.css god-skins.html god-skins.js public
    - cp img/*.png public/img
    - mkdir public/data
    - cp data/gods.json public/data
    - cp data/godswithskins.json public/data
    - cp data/godskins-*.json public/data
    - cp mixercodelog.html public
  artifacts:
    paths:
    - public

deploy_prod:
  stage: deploy
  image: registry.gitlab.com/kissaki/docker-hugo:latest
  before_script:
  - eval $(ssh-agent -s)
  - echo "$SFTP_PRIVKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SFTP_KNOWNHOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - cd public
    - lftp -c "open -u $SFTP_USERNAME,NONE -p $SFTP_PORT sftp://$SFTP_HOST ; mirror --reverse . $SFTP_PATH"
  environment:
    name: production
    url: https://kcode.de/smite/smitegods.html
  only:
    - master
