package autogengods

import ()

type AutoGenerated []struct {
	Ability1x  string `json:"Ability1"`
	Ability2x  string `json:"Ability2"`
	Ability3x  string `json:"Ability3"`
	Ability4x  string `json:"Ability4"`
	Ability5x  string `json:"Ability5"`
	AbilityID1 int    `json:"AbilityId1"`
	AbilityID2 int    `json:"AbilityId2"`
	AbilityID3 int    `json:"AbilityId3"`
	AbilityID4 int    `json:"AbilityId4"`
	AbilityID5 int    `json:"AbilityId5"`
	Ability1   struct {
		Description struct {
			ItemDescription struct {
				Cooldown    string `json:"cooldown"`
				Cost        string `json:"cost"`
				Description string `json:"description"`
				Menuitems   []struct {
					Description string `json:"description"`
					Value       string `json:"value"`
				} `json:"menuitems"`
				Rankitems []struct {
					Description string `json:"description"`
					Value       string `json:"value"`
				} `json:"rankitems"`
				SecondaryDescription string `json:"secondaryDescription"`
			} `json:"itemDescription"`
		} `json:"Description"`
		ID      int    `json:"Id"`
		Summary string `json:"Summary"`
		URL     string `json:"URL"`
	} `json:"Ability_1"`
	Ability2 struct {
		Description struct {
			ItemDescription struct {
				Cooldown    string `json:"cooldown"`
				Cost        string `json:"cost"`
				Description string `json:"description"`
				Menuitems   []struct {
					Description string `json:"description"`
					Value       string `json:"value"`
				} `json:"menuitems"`
				Rankitems []struct {
					Description string `json:"description"`
					Value       string `json:"value"`
				} `json:"rankitems"`
				SecondaryDescription string `json:"secondaryDescription"`
			} `json:"itemDescription"`
		} `json:"Description"`
		ID      int    `json:"Id"`
		Summary string `json:"Summary"`
		URL     string `json:"URL"`
	} `json:"Ability_2"`
	Ability3 struct {
		Description struct {
			ItemDescription struct {
				Cooldown    string `json:"cooldown"`
				Cost        string `json:"cost"`
				Description string `json:"description"`
				Menuitems   []struct {
					Description string `json:"description"`
					Value       string `json:"value"`
				} `json:"menuitems"`
				Rankitems []struct {
					Description string `json:"description"`
					Value       string `json:"value"`
				} `json:"rankitems"`
				SecondaryDescription string `json:"secondaryDescription"`
			} `json:"itemDescription"`
		} `json:"Description"`
		ID      int    `json:"Id"`
		Summary string `json:"Summary"`
		URL     string `json:"URL"`
	} `json:"Ability_3"`
	Ability4 struct {
		Description struct {
			ItemDescription struct {
				Cooldown    string `json:"cooldown"`
				Cost        string `json:"cost"`
				Description string `json:"description"`
				Menuitems   []struct {
					Description string `json:"description"`
					Value       string `json:"value"`
				} `json:"menuitems"`
				Rankitems []struct {
					Description string `json:"description"`
					Value       string `json:"value"`
				} `json:"rankitems"`
				SecondaryDescription string `json:"secondaryDescription"`
			} `json:"itemDescription"`
		} `json:"Description"`
		ID      int    `json:"Id"`
		Summary string `json:"Summary"`
		URL     string `json:"URL"`
	} `json:"Ability_4"`
	Ability5 struct {
		Description struct {
			ItemDescription struct {
				Cooldown    string `json:"cooldown"`
				Cost        string `json:"cost"`
				Description string `json:"description"`
				Menuitems   []struct {
					Description string `json:"description"`
					Value       string `json:"value"`
				} `json:"menuitems"`
				Rankitems []struct {
					Description string `json:"description"`
					Value       string `json:"value"`
				} `json:"rankitems"`
				SecondaryDescription string `json:"secondaryDescription"`
			} `json:"itemDescription"`
		} `json:"Description"`
		ID      int    `json:"Id"`
		Summary string `json:"Summary"`
		URL     string `json:"URL"`
	} `json:"Ability_5"`
	AttackSpeed                int     `json:"AttackSpeed"`
	AttackSpeedPerLevel        float64 `json:"AttackSpeedPerLevel"`
	Cons                       string  `json:"Cons"`
	HP5PerLevel                float64 `json:"HP5PerLevel"`
	Health                     int     `json:"Health"`
	HealthPerFive              int     `json:"HealthPerFive"`
	HealthPerLevel             int     `json:"HealthPerLevel"`
	Lore                       string  `json:"Lore"`
	MP5PerLevel                float64 `json:"MP5PerLevel"`
	MagicProtection            int     `json:"MagicProtection"`
	MagicProtectionPerLevel    int     `json:"MagicProtectionPerLevel"`
	MagicalPower               int     `json:"MagicalPower"`
	MagicalPowerPerLevel       float64 `json:"MagicalPowerPerLevel"`
	Mana                       int     `json:"Mana"`
	ManaPerFive                float64 `json:"ManaPerFive"`
	ManaPerLevel               int     `json:"ManaPerLevel"`
	Name                       string  `json:"Name"`
	OnFreeRotation             string  `json:"OnFreeRotation"`
	Pantheon                   string  `json:"Pantheon"`
	PhysicalPower              int     `json:"PhysicalPower"`
	PhysicalPowerPerLevel      int     `json:"PhysicalPowerPerLevel"`
	PhysicalProtection         int     `json:"PhysicalProtection"`
	PhysicalProtectionPerLevel float64 `json:"PhysicalProtectionPerLevel"`
	Pros                       string  `json:"Pros"`
	Roles                      string  `json:"Roles"`
	Speed                      int     `json:"Speed"`
	Title                      string  `json:"Title"`
	Type                       string  `json:"Type"`
	AbilityDescription1        struct {
		ItemDescription struct {
			Cooldown    string `json:"cooldown"`
			Cost        string `json:"cost"`
			Description string `json:"description"`
			Menuitems   []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"menuitems"`
			Rankitems []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"rankitems"`
			SecondaryDescription string `json:"secondaryDescription"`
		} `json:"itemDescription"`
	} `json:"abilityDescription1"`
	AbilityDescription2 struct {
		ItemDescription struct {
			Cooldown    string `json:"cooldown"`
			Cost        string `json:"cost"`
			Description string `json:"description"`
			Menuitems   []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"menuitems"`
			Rankitems []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"rankitems"`
			SecondaryDescription string `json:"secondaryDescription"`
		} `json:"itemDescription"`
	} `json:"abilityDescription2"`
	AbilityDescription3 struct {
		ItemDescription struct {
			Cooldown    string `json:"cooldown"`
			Cost        string `json:"cost"`
			Description string `json:"description"`
			Menuitems   []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"menuitems"`
			Rankitems []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"rankitems"`
			SecondaryDescription string `json:"secondaryDescription"`
		} `json:"itemDescription"`
	} `json:"abilityDescription3"`
	AbilityDescription4 struct {
		ItemDescription struct {
			Cooldown    string `json:"cooldown"`
			Cost        string `json:"cost"`
			Description string `json:"description"`
			Menuitems   []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"menuitems"`
			Rankitems []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"rankitems"`
			SecondaryDescription string `json:"secondaryDescription"`
		} `json:"itemDescription"`
	} `json:"abilityDescription4"`
	AbilityDescription5 struct {
		ItemDescription struct {
			Cooldown    string `json:"cooldown"`
			Cost        string `json:"cost"`
			Description string `json:"description"`
			Menuitems   []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"menuitems"`
			Rankitems []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"rankitems"`
			SecondaryDescription string `json:"secondaryDescription"`
		} `json:"itemDescription"`
	} `json:"abilityDescription5"`
	BasicAttack struct {
		ItemDescription struct {
			Cooldown    string `json:"cooldown"`
			Cost        string `json:"cost"`
			Description string `json:"description"`
			Menuitems   []struct {
				Description string `json:"description"`
				Value       string `json:"value"`
			} `json:"menuitems"`
			Rankitems            []interface{} `json:"rankitems"`
			SecondaryDescription string        `json:"secondaryDescription"`
		} `json:"itemDescription"`
	} `json:"basicAttack"`
	GodAbility1URL string      `json:"godAbility1_URL"`
	GodAbility2URL string      `json:"godAbility2_URL"`
	GodAbility3URL string      `json:"godAbility3_URL"`
	GodAbility4URL string      `json:"godAbility4_URL"`
	GodAbility5URL string      `json:"godAbility5_URL"`
	GodCardURL     string      `json:"godCard_URL"`
	GodIconURL     string      `json:"godIcon_URL"`
	ID             int         `json:"id"`
	LatestGod      string      `json:"latestGod"`
	RetMsg         interface{} `json:"ret_msg"`
}
