name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Live

    steps:
      - uses: actions/checkout@v2

      - name: SFTP Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TARGET_PATH: ${{ secrets.TARGET_PATH }}
        run: |
          mkdir public public/img public/data
          cp *.html *.css *.js public
          cp roles-pantheons-spritesheet.png 4bfba3d77789a9ec16129032096c7f12.woff public
          cp -r img/* public/img
          cp -r data/*.json public/data
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -k -t 10 -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SFTP_KNOWNHOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          cd public
          lftp -c "open -u $SSH_USERNAME,NONE -p $SSH_PORT sftp://$SSH_HOST ; mirror --reverse . $TARGET_PATH"
          ssh-add -D
